### ISSUE TITLE
Weird Lighting Issue [1.8]

### ISSUE THREAD

**Issue by DatrixTHLK** [Chicken-Bones/CodeChickenCore#55] opened 2015-08-28 02:04 UTC
Whenever I go into the inventory screen the blocks of dirt seem to light up. (For NEI 1.8 latest version)

**Comment by GirafiStudios** [comment] 2015-08-28 02:17
I have already reported this.
Duplicate of https://github.com/Chicken-Bones/NotEnoughItems/issues/243

**Comment by DatrixTHLK** [comment] 2016-10-11 09:44
I see thanks for reporting then

**Closed** 2016-10-23 09:56 UTC
